### ISSUE TITLE
src.config

### ISSUE THREAD

**Issue by Waltj73** [NBA-Betting/NBA_AI#15]
Jeff,

first and foremost, im clueless when it comes to programing

I followed your instructions and am getting this:

Traceback (most recent call last):
  File "C:\Users\walts\NBA_AI\start_app.py", line 24, in <module>
    from src.config import config
  File "C:\Users\walts\NBA_AI\src\config.py", line 26, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

can you help me out if possible

What have i done wrong or what am i missing?
-Walt

**Comment by playoffspalantir** [comment]
I think i got past that part by installing yaml library as well as a few others I did not have previously.

Try: pip install pyyaml
